apiVersion: batch/v1
kind: CronJob
metadata:
  name: printing-job
spec:
  schedule: "42 15 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: printing-job
              image: myjobs:1.0
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure