apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: myjobs-schedule
spec:
  scaleTargetRef:
    name: printing-job
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 60
  triggers:
    - type: cron
      metadata:
        timezone: Asia/Kolkata
        start: 25 16 * * *
        end: 30 16 * * *
        desiredReplicas: "1"